### ISSUE TITLE
font-face mixin — all font formats are mandatory for mixin to work

### ISSUE THREAD

**Issue by kvidek** [degordian/sassbox#1]
mixins/_fonts.scss (L:1)

```
@mixin font-face($font-name, ...) {
    ...
}
```

mixin requires all formats, should ignore if a file format does not exist (e.g. not all fonts have .woff2 format)

**Comment by igorbumba** [comment]
```CSS
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.eot'); /* IE9 Compat Modes */
  src: url('webfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('webfont.woff2') format('woff2'), /* Super Modern Browsers */
       url('webfont.woff') format('woff'), /* Pretty Modern Browsers */
       url('webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('webfont.svg#svgFontName') format('svg'); /* Legacy iOS */
}
```
As you can see **woff2** is for the _Super Modern Browsers_.
I think that this format was meant for the latest release(s) of the browser(s)? New Chrome, Firefox, etc.
